from vk_api.keyboard import VkKeyboard, VkKeyboardColor

start_keyboard = VkKeyboard(one_time=True)
start_keyboard.add_button('Начать', color=VkKeyboardColor.PRIMARY)

menu_keyboard = VkKeyboard(one_time=True)
menu_keyboard.add_button('Обучение', color=VkKeyboardColor.SECONDARY)
menu_keyboard.add_line()
menu_keyboard.add_button('Документы', color=VkKeyboardColor.SECONDARY)
menu_keyboard.add_line()
menu_keyboard.add_button('Студенческая жизнь', color=VkKeyboardColor.SECONDARY)
menu_keyboard.add_line()
menu_keyboard.add_button('Внеучебная деятельность', color=VkKeyboardColor.SECONDARY)
menu_keyboard.add_line()
menu_keyboard.add_button('Прочее', color=VkKeyboardColor.SECONDARY)
menu_keyboard.add_line()
menu_keyboard.add_button('English menu', color=VkKeyboardColor.SECONDARY)
#menu_keyboard.add_openlink_button('Расписание', link='https://table.nsu.ru/faculty/mmf')

study_keyboard = VkKeyboard(one_time=True)
study_keyboard.add_button('Сессия', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Стипендия', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Как попасть на бюджет?', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Хочу отчислиться', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Навигация', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Другое', color=VkKeyboardColor.SECONDARY)
study_keyboard.add_line()
study_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

session_keyboard = VkKeyboard(one_time=True)
session_keyboard.add_button('Что такое допуск к экзамену?', color=VkKeyboardColor.SECONDARY)
session_keyboard.add_line()
session_keyboard.add_button('Как проходит сессия?', color=VkKeyboardColor.SECONDARY)
session_keyboard.add_line()
session_keyboard.add_button('Как проходит экзамен?', color=VkKeyboardColor.SECONDARY)
session_keyboard.add_line()
session_keyboard.add_button('Что делать, если не сдал экзамен?', color=VkKeyboardColor.SECONDARY)
session_keyboard.add_line()
session_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

grant_keyboard = VkKeyboard(one_time=True)
grant_keyboard.add_button('Как получить стипендию?', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Повышенная стипендия', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Когда начисляется стипендия', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Стипендия летом', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Стипендия в академ отпуске', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Стипендия после пересдачи неуд оценки', color=VkKeyboardColor.SECONDARY)
grant_keyboard.add_line()
grant_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

map_keyboard = VkKeyboard(one_time=True)
map_keyboard.add_button('Деканат', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('Как найти нужный кабинет?', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('Где смотреть расписание?', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('Где купить методичку и сувениры?', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('Ближайшие магазины', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('А что покушать?', color=VkKeyboardColor.SECONDARY)
map_keyboard.add_line()
map_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

food_keyboard = VkKeyboard(one_time=True)
food_keyboard.add_button('Где можно поесть?', color=VkKeyboardColor.SECONDARY)
food_keyboard.add_line()
food_keyboard.add_button('Где можно выпить кофе?', color=VkKeyboardColor.SECONDARY)
food_keyboard.add_line()
food_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

another_keyboard = VkKeyboard(one_time=True)
another_keyboard.add_button('Что взять на первую пару?', color=VkKeyboardColor.SECONDARY)
another_keyboard.add_line()
another_keyboard.add_button('Первое занятие физкультуры', color=VkKeyboardColor.SECONDARY)
another_keyboard.add_line()
another_keyboard.add_button('Что делать, если много пропусков физры', color=VkKeyboardColor.SECONDARY)
another_keyboard.add_line()
another_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

docs_keyboard = VkKeyboard(one_time=True)
docs_keyboard.add_button('Как получить справку об обучении?', color=VkKeyboardColor.SECONDARY)
docs_keyboard.add_line()
docs_keyboard.add_button('Военкомат', color=VkKeyboardColor.SECONDARY)
docs_keyboard.add_line()
docs_keyboard.add_button('Потеря пропуска НГУ', color=VkKeyboardColor.SECONDARY)
docs_keyboard.add_line()
docs_keyboard.add_button('Потеря пропуска от общежития', color=VkKeyboardColor.SECONDARY)
docs_keyboard.add_line()
docs_keyboard.add_button('Академотпуск', color=VkKeyboardColor.SECONDARY)
docs_keyboard.add_line()
docs_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

studentlife_keyboard = VkKeyboard(one_time=True)
studentlife_keyboard.add_button('Здоровье', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Иногороднему', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Для чего нужен студенческий', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Где посидеть возле общаг?', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Общежития', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Прачка', color=VkKeyboardColor.SECONDARY)
studentlife_keyboard.add_line()
studentlife_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

health_keyboard = VkKeyboard(one_time=True)
health_keyboard.add_button('Поликлиника', color=VkKeyboardColor.SECONDARY)
health_keyboard.add_line()
health_keyboard.add_button('Где находится травмпункт?', color=VkKeyboardColor.SECONDARY)
health_keyboard.add_line()
health_keyboard.add_button('Мед центр НГУ', color=VkKeyboardColor.SECONDARY)
health_keyboard.add_line()
health_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

nonresident_keyboard = VkKeyboard(one_time=True)
nonresident_keyboard.add_button('Как получить общагу', color=VkKeyboardColor.SECONDARY)
nonresident_keyboard.add_line()
nonresident_keyboard.add_button('Как получить временную прописку', color=VkKeyboardColor.SECONDARY)
nonresident_keyboard.add_line()
nonresident_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

time_keyboard = VkKeyboard(one_time=True)
time_keyboard.add_button('Общественная деятельность', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Студенченские отряды', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Иностранные языки', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Кружки', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Спорт', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Где узнать о мероприятиях?', color=VkKeyboardColor.SECONDARY)
time_keyboard.add_line()
time_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

mugs_keyboard = VkKeyboard(one_time=True)
mugs_keyboard.add_button('Музыка', color=VkKeyboardColor.SECONDARY)
mugs_keyboard.add_line()
mugs_keyboard.add_button('Журналистика', color=VkKeyboardColor.SECONDARY)
mugs_keyboard.add_line()
mugs_keyboard.add_button('Интеллектуальные игры', color=VkKeyboardColor.SECONDARY)
mugs_keyboard.add_line()
mugs_keyboard.add_button('Computer Science center', color=VkKeyboardColor.SECONDARY)
mugs_keyboard.add_line()
mugs_keyboard.add_button('Юмор', color=VkKeyboardColor.SECONDARY)
mugs_keyboard.add_line()
mugs_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

sport_keyboard = VkKeyboard(one_time=True)
sport_keyboard.add_button('Бани', color=VkKeyboardColor.SECONDARY)
sport_keyboard.add_line()
sport_keyboard.add_button('Бассейн, режим работы, цены', color=VkKeyboardColor.SECONDARY)
sport_keyboard.add_line()
sport_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

other_keyboard = VkKeyboard(one_time=True)
other_keyboard.add_button('Как попасть в НГУ, если забыл пропуск', color=VkKeyboardColor.SECONDARY)
other_keyboard.add_line()
other_keyboard.add_button('Как добраться до НГУ', color=VkKeyboardColor.SECONDARY)
other_keyboard.add_line()
other_keyboard.add_button('Где можно распечатать?', color=VkKeyboardColor.SECONDARY)
other_keyboard.add_line()
other_keyboard.add_button('Не могу зайти на почту', color=VkKeyboardColor.SECONDARY)
other_keyboard.add_line()
other_keyboard.add_button('Помощь психолога', color=VkKeyboardColor.SECONDARY)
other_keyboard.add_line()
other_keyboard.add_button('Назад', color=VkKeyboardColor.NEGATIVE)

menu_keyboard_en = VkKeyboard(one_time=True)
menu_keyboard_en.add_button('Certificate that I am studying at NSU', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('How to find the required office?', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('Timetable', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('Where can I print?', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('lost my NSU card', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('Next', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en.add_line()
menu_keyboard_en.add_button('Back', color=VkKeyboardColor.NEGATIVE)

menu_keyboard_en_next = VkKeyboard(one_time=True)
menu_keyboard_en_next.add_button('Pay for the dormitory', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en_next.add_line()
menu_keyboard_en_next.add_button('Lost my dorm card', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en_next.add_line()
menu_keyboard_en_next.add_button('Forgot my NSU ID', color=VkKeyboardColor.SECONDARY)
menu_keyboard_en_next.add_line()
menu_keyboard_en_next.add_button("Dean's office", color=VkKeyboardColor.SECONDARY)
menu_keyboard_en_next.add_line()
menu_keyboard_en_next.add_button('Back', color=VkKeyboardColor.NEGATIVE)